version: "3.8"

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.4
    ports:
      - "8080:8042"     # Web UI and RESTful services
      - "4242:4242"     # DICOM port
    volumes:
      - orthanc_storage:/var/lib/orthanc/db
      - ./orthanc-config.json:/etc/orthanc/orthanc.json:ro
    restart: unless-stopped

volumes:
  orthanc_storage: